### ISSUE TITLE
How to print objective function value (tour cost) of testing set

### ISSUE THREAD

**Issue by pablcab** [TimD3/Moco#1]
I am currently comparing different RL methods for solving TSPLIB instances. I have been able to run evaluate_tsp.py on several TSPLIB instances, but I don't know how to print the objective function value (tour cost) obtained (the code only shows the rewards and compilation time).

I hope someone can help with this. Thank you in advance.

**Comment by TimD3** [comment]
In this case the reward, as logged in the mlflow dashboard should reflect the tour cost. Just be aware that the models were not trained for TSPLIB instances. Additionally, we use a simple knn sparsification as it makes the code easier and we were benchmarking only with the uniform instances. It is possible however that e.g. an instance with two very separated clusters as might appear in TSPLIB becomes infeasible after sparsification. Currently we add a penalty on the reward of $n\sqrt{2}$, where $n$ is the number of unvisited cities left, in case the model produces an infeasible solution.
